### ISSUE TITLE
Selected channel name should be displayed while watching

### ISSUE THREAD

**Issue by sevketarisu** [CS576-SEVKET-CEREN-GOKHAN-OMERCAN/LiveVideoStreamProject#4]
Selected channel name should be displayed while watching the broadcasting video

![image](https://cloud.githubusercontent.com/assets/11589446/10727700/91571cfe-7be4-11e5-8f79-c9fba0c60c51.png)

**Comment by oyuksel** [comment]
İssue çözüldü.

**Comment by sevketarisu** [comment]
tested
